# Generated by Django 3.2.5 on 2021-08-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('C', 'Cohort'), ('M', 'Mentors'), ('P', 'Pilbara')], default='P', max_length=200),
        ),
    ]
